server:
  port: 9055


spring:
  application:
    name: order-consumer
  cloud:
    nacos:
      server-addr:  127.0.0.1:8848
      discovery:
        username: nacos
        password: nacos
        namespace: public
logging:
  level:
    com.example.hzsfeign.Clients.OrderClients: debug

feign:
  feign:
    client:
      config:
        OrderService:
          loggerLevel: BASIC
          # 连接超时时间，默认是2s
          connectTimeout: 5000
          # 请求处理超时时间，默认是5s
          readTimeout: 3000
  enabled: true

